#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CitraRooms.Resource", IsApplication=true)]

namespace CitraRooms
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_citra = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_exit_to_app_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_info_outline_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_lock = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_send_white_48dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_settings_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int shape_circle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int shape_rect_round_corner = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int centerLayout = 2131165205;
			
			// aapt resource value: 0x7f070007
			public const int connectingLayout = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int defPassword = 2131165195;
			
			// aapt resource value: 0x7f07001c
			public const int dialog_gameImage = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int dialog_gameLabel = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int dialog_ownerLabel = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int dialog_playerCounter = 2131165216;
			
			// aapt resource value: 0x7f07001d
			public const int dialog_roomLabel = 2131165213;
			
			// aapt resource value: 0x7f07001b
			public const int enterRoom = 2131165211;
			
			// aapt resource value: 0x7f070014
			public const int gameImage = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int gameLabel = 2131165207;
			
			// aapt resource value: 0x7f070023
			public const int infoButton = 2131165219;
			
			// aapt resource value: 0x7f07001a
			public const int infoPlayers = 2131165210;
			
			// aapt resource value: 0x7f070001
			public const int listRooms = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int loadingPage = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int message = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int messageAlert = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int messages = 2131165190;
			
			// aapt resource value: 0x7f070022
			public const int openSetting = 2131165218;
			
			// aapt resource value: 0x7f070018
			public const int ownerLabel = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int playerGame = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int playerName = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int player_gameImage = 2131165201;
			
			// aapt resource value: 0x7f070019
			public const int playersCounter = 2131165209;
			
			// aapt resource value: 0x7f070021
			public const int playersList = 2131165217;
			
			// aapt resource value: 0x7f070003
			public const int progressBar1 = 2131165187;
			
			// aapt resource value: 0x7f070016
			public const int roomLabel = 2131165206;
			
			// aapt resource value: 0x7f070005
			public const int scrollMessages = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int sendMessageButton = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int textMessage = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int timeAlert = 2131165197;
			
			// aapt resource value: 0x7f070010
			public const int timeMessage = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int username = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int usernameMessage = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_room = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_settings = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int layout_chat_alert = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int layout_message = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int layout_player = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int layout_room = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int layout_sent_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int players_dialog = 2130968584;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu_main = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int menu_room = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int sound_in = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
